import sys
from common.singletons import Singletons

class GLFWError(Exception):...
class OpenGLError(Exception):...
class AssetError(Exception):...
class TextureError(Exception):...
class ShaderError(Exception):...
class GatorError(Exception):...
class SingletonError(Exception):...
class GraphicsError(Exception):...

def fatal(type: type[Exception], message: str):
    print(type.__name__+": "+message)
    if Singletons.editor:
        Singletons.editor.destroy()
    elif Singletons.app:
        Singletons.app.destroy()
    sys.exit(-1)
    
def warning(type: type[Exception], message):
    print(type.__name__+": "+message)
    